### ISSUE TITLE
Exception while running the sample (missing "init.min.js")

### ISSUE THREAD

**Issue by dima-zemingo** [andycandy-de/SimpleAndroidBridge#1] opened 2021-05-02 08:52 UTC
Process: de.andycandy.android.bridge.example, PID: 4624
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.io.FileNotFoundException: init.min.js
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:874)
        at android.content.res.AssetManager.open(AssetManager.java:851)
        at de.andycandy.android.bridge.InnerBridge.readInitScript(Bridge.kt:307)
        at de.andycandy.android.bridge.InnerBridge.init(Bridge.kt:48)
        at de.andycandy.android.bridge.Bridge.init(Bridge.kt:23)
        at de.andycandy.android.bridge.example.MainActivity$onCreate$1.onPageStarted(MainActivity.kt:44)
        at Fa.c(chromium-TrichromeWebViewGoogle.apk-stable-410410681:2)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:162)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)

**Comment by andycandy-de** [comment] 2021-05-02 12:11
Thank you for reporting. I think gradle didn't build all sub projects. The SimpleAndoirdBridgeLib project depends on the SimpleAndoirdBridgeLibJS project. The task 'compileJs' of the SimpleAndoirdBridgeLibJS must be executed. That's defined in the SimpleAndoirdBridgeLib build.gradle. I can imagine that android studio didn't resolved the full build successfull.
Could you try to run the build task of the SimpleAndoirdBridgeLib sub project? ```gradle build```

**Comment by dima-zemingo** [comment] 2021-05-04 11:41
> 
> 
> Thank you for reporting. I think gradle didn't build all sub projects. The SimpleAndoirdBridgeLib project depends on the SimpleAndoirdBridgeLibJS project. The task 'compileJs' of the SimpleAndoirdBridgeLibJS must be executed. That's defined in the SimpleAndoirdBridgeLib build.gradle. I can imagine that android studio didn't resolved the full build successfull.
> Could you try to run the build task of the SimpleAndoirdBridgeLib sub project? `gradle build`

I've rebuild it several times, nothing changed... and i didnt see the compileJS gradle task in the gradle scripts

**Comment by andycandy-de** [comment] 2021-05-05 12:08
The ```compileJS``` task is part of of the plugin ```com.leobia.gradle.jsgradlecompiler``` - https://github.com/andycandy-de/SimpleAndroidBridge/blob/development/SimpleAndoirdBridgeLibJS/build.gradle

In the project 'SimpleAndoirdBridgeLib' is defined that the project depends on this task - https://github.com/andycandy-de/SimpleAndroidBridge/blob/development/SimpleAndoirdBridgeLib/build.gradle

```
task copyInitJS {
    dependsOn(':SimpleAndoirdBridgeLibJS:compileJs', cleanAssets)
    doLast {
        copy {
            from file('./../SimpleAndoirdBridgeLibJS/build/js')
            into file('./src/main/assets')
        }
    }
}

preBuild.dependsOn copyInitJS
```

I was able to reproduce the error and I changed that the task 'preBuild' depends on 'copyInitJS'. Before the task 'build' was defined

before
```
build.dependsOn copyInitJS
```

after
```
preBuild.dependsOn copyInitJS
```

For me that worked. Would be great if you can say me if that also solved your issue.

**Comment by andycandy-de** [comment] 2021-05-30 23:02
I close this issue because the change works for me and @dima-zemingo doesn't response.

**Closed as completed by andycandy-de** 2021-05-30 23:02 UTC
